import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import OBR from'@owlbear-rodeo/sdk';
import'./style.css';
import{ABILITIES,RELICS,RITUALS,BG_FLAWS,BG_MARKS,BG_IDIO,BG_EVENTS,BG_IMPORTANT,BG_WHO,WEAPONS,BRAWLER_WEAPONS,ARMOR,HATS,GEAR,STRASAK_AFFLICTIONS,SEA_ORIGINS,THINKING_ANIMALS,START_LUGGAGE,START_CHEAP,START_USEFUL,CatalogItem}from'./data';

type Item={id:string;name:string;detail?:string;damage?:string;qty?:number;size?:number;level?:string};
type RollEntry={id:string;character:string;label:string;die:number;mod:number;total:number;at:number;luck?:boolean;misfortune?:boolean};
const ROLL_CHANNEL='cz.pirateborg.sheet/roll';
const ROLL_HISTORY_KEY='cz.pirateborg.sheet/roll-history';
type Sheet={name:string;classes:string[];stats:Record<string,number>;hp:[number,number];gifts:[number,number];giftDie:string;silver:number;abilities:Item[];relics:Item[];rituals:Item[];ritualUse:[number,number];prayerUse:[number,number];spellUse:[number,number];melee:Item[];ranged:Item[];ammo:Item[];armor:Item[];hats:Item[];gear:Item[];notes:string;background:Record<string,string>};
const uid=()=>Math.random().toString(36).slice(2,9);
const CLASS_OPTIONS=['Suchozemec','Rváč','Darebák','Bukanýr','Švihák','Zélóta','Kouzelník','Strašák','Bytost z báchorek'];
const CLASS_RULES:Record<string,{mods:Record<string,number>;hpDie:number;giftDie:string;summary:string}>={
  'Suchozemec':{mods:{},hpDie:10,giftDie:'k2',summary:'Bez povolání. ŽV k10 ± Odolnost; zbraň k10, klobouk k12, oblečení k10, Ďáblovy dary k2.'},
  'Rváč':{mods:{Síla:1,Odolnost:1,Bystrost:-1,Vůle:-1},hpDie:12,giftDie:'k2',summary:'Síla +1, Odolnost +1, Bystrost −1, Vůle −1. ŽV k12 ± Odolnost; zbraň k6, oblečení k10, klobouk k12, Ďáblovy dary k2.'},
  'Darebák':{mods:{Obratnost:2,Síla:-1,Odolnost:-1},hpDie:8,giftDie:'k2',summary:'Obratnost +2, Síla −1, Odolnost −1. ŽV k8 ± Odolnost; zbraň k6, oblečení k6, klobouk k10, Ďáblovy dary k2.'},
  'Bukanýr':{mods:{Bystrost:2,Obratnost:-1,Vůle:-1},hpDie:8,giftDie:'k2',summary:'Bystrost +2, Obratnost −1, Vůle −1. ŽV k8 ± Odolnost; mušketa, oblečení k10, klobouk k12, Ďáblovy dary k2.'},
  'Švihák':{mods:{Síla:1,Obratnost:1,Bystrost:-1,Vůle:-1},hpDie:10,giftDie:'k2',summary:'Síla +1, Obratnost +1, Bystrost −1, Vůle −1. ŽV k10 ± Odolnost; zbraň k10, oblečení k10, klobouk k12, Ďáblovy dary k2.'},
  'Zélóta':{mods:{Vůle:2,Obratnost:-1,Odolnost:-1},hpDie:8,giftDie:'k4',summary:'Vůle +2, Obratnost −1, Odolnost −1. ŽV k8 ± Odolnost; zbraň k8, oblečení k8, Ďáblovy dary k4.'},
  'Kouzelník':{mods:{Vůle:2,Síla:-1,Odolnost:-1},hpDie:8,giftDie:'k4',summary:'Vůle +2, Síla −1, Odolnost −1. ŽV k8 ± Odolnost; dřevěný nůž nebo lanový utahovák k4, oblečení k6, Ďáblovy dary k4.'},
  'Strašák':{mods:{},hpDie:8,giftDie:'k2',summary:'Hoď k6 na postižení a k6 na další povolání. Konkrétní hodnoty vycházejí z dalšího povolání.'},
  'Bytost z báchorek':{mods:{},hpDie:8,giftDie:'k2',summary:'Mořan, Vodní mutant nebo Myslící zvíře. Hodnoty závisejí na konkrétním výsledku.'}
};
const classInfo=(name:string)=>CLASS_RULES[name]?.summary||'Vlastní nebo domácí povolání.';
const initial:Sheet={name:'',classes:[],stats:{Síla:0,Obratnost:0,Bystrost:0,Odolnost:0,Vůle:0},hp:[8,8],gifts:[1,1],giftDie:'k2',silver:0,abilities:[],relics:[],rituals:[],ritualUse:[0,0],prayerUse:[0,0],spellUse:[0,0],melee:[],ranged:[],ammo:[],armor:[],hats:[],gear:[],notes:'',background:{'Kdo jsi?':'','Charakterová vada':'','Poznávací znamení':'','Idiosynkrazie':'','Nešťastné události a stavy':'','Důležitá věc':''}};
const load=()=>{try{const x=JSON.parse(localStorage.getItem('pirate-borg-sheet')||'null');return x?{...initial,...x,background:{...initial.background,...(x.background||{})},prayerUse:x.prayerUse||(x.classes?.includes('Zélóta')?x.magicUse:[0,0])||[0,0],spellUse:x.spellUse||(x.classes?.includes('Kouzelník')?x.magicUse:[0,0])||[0,0]}:initial}catch{return initial}};
function Num({v,set}:{v:number,set:(n:number)=>void}){return <span className="num"><button aria-label="Snížit" onClick={()=>set(v-1)}>−</button><input type="number" value={v} onChange={e=>set(+e.target.value)}/><button aria-label="Zvýšit" onClick={()=>set(v+1)}>+</button></span>}
function List({title,items,setItems,kind='plain',info,catalog=[],catalogId}:{title:string;items:Item[];setItems:(x:Item[])=>void;kind?:'plain'|'weapon'|'ammo'|'gear'|'armor';info?:string;catalog?:CatalogItem[];catalogId?:string}){const listId='cat-'+(catalogId||title||'items').replace(/\W/g,'');const patch=(id:string,p:Partial<Item>)=>setItems(items.map(x=>x.id===id?{...x,...p}:x));const nameChange=(x:Item,name:string)=>{const found=catalog.find(c=>c.name===name);patch(x.id,found?{name,detail:found.detail,level:found.level??x.level,damage:found.damage??x.damage,size:found.size??x.size}:{name})};return <section className="list">{title&&<h3>{title}{info&&<span className="tip" title={info}>ⓘ</span>}</h3>}{catalog.length>0&&<datalist id={listId}>{catalog.map((c,i)=><option key={c.name+i} value={c.name} label={c.label||c.name}/>)}</datalist>}{items.map(x=><div className={'row '+kind} key={x.id}><input className="grow" list={catalog.length?listId:undefined} placeholder="Název" value={x.name} onChange={e=>nameChange(x,e.target.value)}/>{x.level!==undefined&&kind==='plain'&&<input className="tiny" title="Úroveň" placeholder="I" value={x.level||''} onChange={e=>patch(x.id,{level:e.target.value})}/>} {kind==='armor'&&<input className="tiny" placeholder="Úr." value={x.level||''} onChange={e=>patch(x.id,{level:e.target.value})}/>} {(kind==='weapon'||kind==='ammo')&&<input className="small" placeholder="Zranění" value={x.damage||''} onChange={e=>patch(x.id,{damage:e.target.value})}/>} {kind==='ammo'&&<input className="tiny" type="number" placeholder="Počet" value={x.qty??0} onChange={e=>patch(x.id,{qty:+e.target.value})}/>} {(kind==='weapon'||kind==='ammo'||kind==='gear')&&<input className="tiny" type="number" title="Velikost" value={x.size??0} onChange={e=>patch(x.id,{size:+e.target.value})}/>} {kind!=='gear'&&<input className="detail" title={x.detail||''} placeholder="Vlastnosti / popis" value={x.detail||''} onChange={e=>patch(x.id,{detail:e.target.value})}/>}<button className="x" title="Odstranit" aria-label="Odstranit položku" onClick={()=>setItems(items.filter(i=>i.id!==x.id))}>×</button></div>)}<button className="add" onClick={()=>setItems([...items,{id:uid(),name:'',qty:kind==='gear'||kind==='ammo'?1:undefined,size:['weapon','ammo','gear'].includes(kind)?1:undefined}])}>＋ Přidat</button></section>}
function RollModal({label,result,mod,onClose}:{label:string;result:number;mod?:number;onClose:()=>void}){const total=result+(mod||0);return <div className="veil" onClick={onClose}><div className="rollCard" onClick={e=>e.stopPropagation()}><button className="closeRoll" onClick={onClose}>×</button><div className="rollKicker">HOD K20</div><div className="rollLabel">{label}</div><div className="rollResult">{result}</div>{mod!==undefined&&<><div className="rollMod">{result} {mod>=0?'+':'−'} {Math.abs(mod)} = <b>{total}</b></div>{result===20&&<div className="rollSpecial">ŠTĚSTÍ</div>}{result===1&&<div className="rollSpecial">SMŮLA</div>}</>}<button className="rollOk" onClick={onClose}>ZAVŘÍT</button></div></div>}
const pick=<T,>(a:T[])=>a[Math.floor(Math.random()*a.length)];
const itemFrom=(c:CatalogItem):Item=>({id:uid(),name:c.name,detail:c.detail,damage:c.damage,size:c.size,level:c.level});
const armorRoll=(die:number)=>{const r=Math.ceil(Math.random()*die);const idx=r<=2?0:r<=4?1:r===5?2:r===6?3:r===7?4:r===8?5:r===9?6:7;return itemFrom(ARMOR[idx])};
const hatRoll=(die:number)=>{const r=Math.ceil(Math.random()*die);const idx=r<=4?0:r===5?1:r===6?2:r===7?3:r===8?4:r===9?5:r===10?6:r===11?7:8;return itemFrom(HATS[idx])};
const startAbility=(cls:string)=>{const prefix:Record<string,string>={'Darebák':'Darebák','Bukanýr':'Bukanýr','Švihák':'Švihák','Zélóta':'Zélóta','Kouzelník':'Kouzelník'};const p=prefix[cls];if(!p)return null;const pool=ABILITIES.filter(a=>a.detail.startsWith(p+' —'));return pool.length?itemFrom(pick(pool)):null};
const startWeapon=(cls:string):{item:Item;ranged:boolean;ammo?:Item}|null=>{if(cls==='Rváč')return {item:itemFrom(pick(BRAWLER_WEAPONS)),ranged:false};if(cls==='Bukanýr'){const w=WEAPONS.find(x=>x.name==='Mušketa')!;return {item:itemFrom(w),ranged:true,ammo:{id:uid(),name:'Kulky',qty:10,damage:'—',detail:'Počet při tvorbě: 10 + Bystrost.',size:1}}}if(cls==='Kouzelník'){return {item:{id:uid(),name:Math.random()<.5?'Dřevěný nůž':'Lanový kolík',damage:'k4',detail:'Počáteční zbraň Kouzelníka.',size:1},ranged:false}}const dice:Record<string,number>={'Suchozemec':10,'Darebák':6,'Švihák':10,'Zélóta':8};const die=dice[cls];if(!die)return null;const pool=WEAPONS.slice(0,die);const w=pick(pool);return {item:itemFrom(w),ranged:['Vrhací nůž','Foukačka','Vrhací sekera','Střílecí harpuna','Křesadlová pistole','Trombón','Mušketa','Bukanýrská mušketa'].includes(w.name)}};
const NORMAL_CLASSES=['Rváč','Darebák','Bukanýr','Švihák','Zélóta','Kouzelník'];
const animalRules:Record<string,{mods:Record<string,number>;hpDie:number;giftDie:string;attack:string}>={
'Záludná slepice':{mods:{Vůle:3},hpDie:4,giftDie:'k4',attack:'Klovnutí k2'},'Jaguár':{mods:{Síla:2,Obratnost:2},hpDie:8,giftDie:'k4',attack:'Kousnutí/drápy k8'},'Krokodýl':{mods:{Síla:3,Odolnost:1},hpDie:10,giftDie:'k4',attack:'Kousnutí k10'},'Krysa':{mods:{Obratnost:3,Odolnost:2},hpDie:2,giftDie:'k4',attack:'Nakažlivé kousnutí k2'},'Papoušek pro štěstí':{mods:{Obratnost:1,Bystrost:2},hpDie:2,giftDie:'k6',attack:'Klovnutí k4'},'Mazaná opice':{mods:{Síla:-1,Obratnost:2,Bystrost:0},hpDie:6,giftDie:'k4',attack:'Kousnutí k4'}};
function App(){const[s,setS]=useState<Sheet>(load);const[bg,setBg]=useState(false);const[notes,setNotes]=useState(false);const[roll,setRoll]=useState<{label:string,result:number,mod?:number}|null>(null);useEffect(()=>{localStorage.setItem('pirate-borg-sheet',JSON.stringify(s))},[s]);useEffect(()=>{OBR.onReady(()=>OBR.action.setWidth(720))},[]);const patch=(p:Partial<Sheet>)=>setS({...s,...p});
const addStartGear=()=>{let gear=[...s.gear,itemFrom(pick(START_LUGGAGE)),itemFrom(pick(START_CHEAP))];const useful=pick(START_USEFUL);let relics=[...s.relics];if(useful.name==='Náhodná starobylá relikvie')relics.push(itemFrom(pick(RELICS)));else gear.push(itemFrom(useful));patch({gear,relics});};

const applyBaseStart=(base:Sheet,cls:string):Sheet=>{const rule=CLASS_RULES[cls];if(!rule)return base;let stats={...base.stats};Object.entries(rule.mods).forEach(([k,v])=>stats[k]=(stats[k]||0)+v);const hp=Math.max(1,Math.ceil(Math.random()*rule.hpDie)+(stats.Odolnost||0));const gd=Number(rule.giftDie.slice(1))||2;const gifts=Math.ceil(Math.random()*gd);let melee=[...base.melee],ranged=[...base.ranged],ammo=[...base.ammo],armor=[...base.armor],hats=[...base.hats],abilities=[...base.abilities];const w=startWeapon(cls);if(w){(w.ranged?ranged:melee).push(w.item);if(w.ammo){w.ammo.qty=10+(stats.Bystrost||0);ammo.push(w.ammo)}}const armorDice:Record<string,number>={'Suchozemec':10,'Rváč':10,'Darebák':6,'Bukanýr':10,'Švihák':10,'Zélóta':8,'Kouzelník':6};if(armorDice[cls])armor.push(armorRoll(armorDice[cls]));const hatDice:Record<string,number>={'Suchozemec':12,'Rváč':12,'Darebák':10,'Bukanýr':12,'Švihák':12};if(hatDice[cls])hats.push(hatRoll(hatDice[cls]));const a=startAbility(cls);if(a)abilities.push(a);const dailyMax=(cls==='Zélóta'||cls==='Kouzelník')?Math.max(0,Math.ceil(Math.random()*2)+(stats.Vůle||0)):0;const prayerUse=cls==='Zélóta'?[dailyMax,dailyMax] as [number,number]:base.prayerUse;const spellUse=cls==='Kouzelník'?[dailyMax,dailyMax] as [number,number]:base.spellUse;return {...base,stats,hp:[hp,hp],gifts:[gifts,gifts],giftDie:rule.giftDie,melee,ranged,ammo,armor,hats,abilities,prayerUse,spellUse};};
const changeClass=(i:number,next:string)=>{const prev=s.classes[i]||'';const prevRule=CLASS_RULES[prev];let base={...s,classes:s.classes.map((x,j)=>j===i?next:x),stats:{...s.stats}};if(prevRule)Object.entries(prevRule.mods).forEach(([k,v])=>base.stats[k]=(base.stats[k]||0)-v);if(next==='Strašák'&&prev!==next){const aff=itemFrom(pick(STRASAK_AFFLICTIONS)),normal=pick(NORMAL_CLASSES);base={...base,classes:[...base.classes,normal],abilities:[...base.abilities,aff]};setS(applyBaseStart(base,normal));return;}if(next==='Bytost z báchorek'&&prev!==next){const roll=Math.ceil(Math.random()*6);if(roll<=2){const normal=pick(NORMAL_CLASSES);base={...base,classes:[...base.classes,normal],abilities:[...base.abilities,itemFrom(SEA_ORIGINS[0])]};setS(applyBaseStart(base,normal));return;}if(roll<=4){const origin=pick(SEA_ORIGINS.slice(1)),normal=pick(NORMAL_CLASSES);if(origin.name==='Elektrický úhoř')base.stats.Obratnost+=1;base={...base,classes:[...base.classes,normal],abilities:[...base.abilities,itemFrom(origin)],rituals:origin.name==='Velký Prastarý'?[...base.rituals,itemFrom(pick(RITUALS))]:base.rituals};setS(applyBaseStart(base,normal));return;}const animal=pick(THINKING_ANIMALS),ar=animalRules[animal.name];Object.entries(ar.mods).forEach(([k,v])=>base.stats[k]=(base.stats[k]||0)+v);const hp=Math.max(1,Math.ceil(Math.random()*ar.hpDie)+(base.stats.Odolnost||0)),gd=Number(ar.giftDie.slice(1)),gifts=Math.ceil(Math.random()*gd);let melee=[...base.melee,{id:uid(),name:ar.attack.split(' k')[0],damage:'k'+ar.attack.split(' k')[1],detail:'Přirozená zbraň.',size:0}],ranged=[...base.ranged],relics=[...base.relics],rituals=[...base.rituals];if(animal.name==='Záludná slepice'){relics.push(itemFrom(pick(RELICS)));rituals.push(itemFrom(pick(RITUALS)))}if(animal.name==='Mazaná opice'){const w=startWeapon('Suchozemec');if(w)(w.ranged?ranged:melee).push(w.item)}setS({...base,hp:[hp,hp],gifts:[gifts,gifts],giftDie:ar.giftDie,abilities:[...base.abilities,itemFrom(animal)],relics,rituals,melee,ranged});return;}if(CLASS_RULES[next]&&next!==prev){setS(applyBaseStart(base,next));return;}setS(base);};
const loadSum=useMemo(()=>[...s.melee,...s.ranged,...s.ammo,...s.gear].reduce((a,x)=>a+(x.size||0),0),[s]);const cap=8+s.stats.Síla;const overloaded=loadSum>cap;const abilityText=(x:Item)=>`${x.detail||''} ${ABILITIES.find(a=>a.name===x.name)?.detail||''}`;const hasPrayer=s.classes.includes('Zélóta')||s.abilities.some(x=>abilityText(x).includes('Zélóta — Modlitba'));const hasSpell=s.classes.includes('Kouzelník')||s.abilities.some(x=>abilityText(x).includes('Kouzelník — Kouzlo'));return <main><div className="hero"><img className="pbLogo" src="/pirate-borg-logo.png" alt="Pirate Borg"/></div><div className="sheetTitle">DENÍK POSTAVY</div><header><input className="name" placeholder="JMÉNO" value={s.name} onChange={e=>patch({name:e.target.value})}/></header><div className="classes"><b>POVOLÁNÍ</b>{s.classes.map((c,i)=><span className="classEntry" key={i}><input list="classes" placeholder="Vyber nebo napiš" value={c} onChange={e=>changeClass(i,e.target.value)}/><span className="tip classTip" title={classInfo(c)}>ⓘ</span><button className="x" title="Odstranit povolání" onClick={()=>{const r=CLASS_RULES[c];let stats={...s.stats};if(r)Object.entries(r.mods).forEach(([k,v])=>stats[k]=(stats[k]||0)-v);patch({classes:s.classes.filter((_,j)=>j!==i),stats})}}>×</button></span>)}<datalist id="classes">{CLASS_OPTIONS.map(x=><option value={x} key={x}/>)}</datalist><button className="addClass" title="Přidat povolání" onClick={()=>patch({classes:[...s.classes,'']})}>＋</button><button className="resetCharacter" title="Začít s úplně novou postavou" onClick={()=>{if(window.confirm('Opravdu chceš vymazat všechny údaje postavy? Tuto akci nelze vrátit.')){setS({...initial,stats:{...initial.stats},hp:[0,0],gifts:[0,0],background:{...initial.background}});setNotes(false);setBg(false)}}}>NOVÁ POSTAVA</button></div>
<div className="topgrid"><section><h2>VLASTNOSTI</h2>{Object.entries(s.stats).map(([k,v])=><div className="stat" key={k}><b>{k.toUpperCase()}</b><input type="number" min="-3" max="6" value={v} onChange={e=>patch({stats:{...s.stats,[k]:+e.target.value}})}/><button className="test" onClick={()=>doTest(k,v)}>TEST</button></div>)}</section><section className="resources"><div className="resourceBlock"><h2>ŽIVOTY</h2><div className="resourceValue"><Num v={s.hp[0]} set={n=>patch({hp:[n,s.hp[1]]})}/> <span>/</span> <input className="tiny" type="number" value={s.hp[1]} onChange={e=>patch({hp:[s.hp[0],+e.target.value]})}/></div></div><div className="resourceBlock"><h2>ĎÁBLOVY DARY</h2><div className="resourceValue"><Num v={s.gifts[0]} set={n=>patch({gifts:[n,s.gifts[1]]})}/> <span>/</span> <input className="tiny" type="number" value={s.gifts[1]} onChange={e=>patch({gifts:[s.gifts[0],+e.target.value]})}/></div><label className="recovery">Obnova <input className="small" value={s.giftDie} onChange={e=>patch({giftDie:e.target.value})}/></label></div><div className="resourceBlock carry"><h2>NOSNOST</h2><div className="carryValue"><b>{loadSum} / {cap}</b> <span className="tip" title="Velikost: 0 = drobný, 1 = běžně velký, 2 a více = velký. Běžná nosnost je 8 + Síla; maximum je dvojnásobek.">ⓘ</span></div>{overloaded&&<p>Přetížení, +2 OB k testům Síly a Obratnosti.</p>}<small>Maximum: {cap*2}</small></div></section></div>
<section className="abilitiesFull"><div className="abilityHead"><h2>SCHOPNOSTI</h2><div className="dailyCounters">{hasPrayer&&<span className="dailyMagic"><b>MODLITBY:</b> <Num v={s.prayerUse[0]} set={n=>patch({prayerUse:[n,s.prayerUse[1]]})}/> / <input className="tiny" type="number" value={s.prayerUse[1]} onChange={e=>patch({prayerUse:[s.prayerUse[0],+e.target.value]})}/><small>k2 + Vůle za den • obnova za úsvitu</small></span>}{hasSpell&&<span className="dailyMagic"><b>KOUZLA:</b> <Num v={s.spellUse[0]} set={n=>patch({spellUse:[n,s.spellUse[1]]})}/> / <input className="tiny" type="number" value={s.spellUse[1]} onChange={e=>patch({spellUse:[s.spellUse[0],+e.target.value]})}/><small>k2 + Vůle za den • obnova při západu slunce</small></span>}</div></div><List title="" catalog={ABILITIES} catalogId="abilities" items={s.abilities} setItems={x=>patch({abilities:x})}/></section>
<section className="relicFull"><List title="RELIKVIE" catalog={RELICS} catalogId="relics" info="Relikvie se aktivují akcí; po použití následuje test Vůle OB12." items={s.relics} setItems={x=>patch({relics:x})}/></section><section className="ritualFull"><div className="ritualHead"><h2>RITUÁLY</h2><div className="ritualCounter"><Num v={s.ritualUse[0]} set={n=>patch({ritualUse:[n,s.ritualUse[1]]})}/> / <input className="tiny" type="number" value={s.ritualUse[1]} onChange={e=>patch({ritualUse:[s.ritualUse[0],+e.target.value]})}/><span className="tip" title="Každé svítání k4 + Vůle. Seslání stojí akci a test Vůle OB12; úspěch odečte 1 použití.">ⓘ</span><small>k4 + Vůle za den</small></div></div><List title="" catalog={RITUALS} catalogId="rituals" items={s.rituals} setItems={x=>patch({rituals:x})}/></section>
<section className="weapons"><h2>ZBRANĚ</h2><List title="ZBLÍZKA" kind="weapon" catalog={WEAPONS} catalogId="melee" items={s.melee} setItems={x=>patch({melee:x})}/><List title="NA DÁLKU" kind="weapon" catalog={WEAPONS} catalogId="ranged" items={s.ranged} setItems={x=>patch({ranged:x})}/><List title="STŘELY A BOMBY" kind="ammo" items={s.ammo} setItems={x=>patch({ammo:x})}/></section>
<div className="twocol"><List title="OBLEČENÍ / ZBROJ" kind="armor" catalog={ARMOR} catalogId="armor" items={s.armor} setItems={x=>patch({armor:x})}/><List title="KLOBOUKY" kind="armor" catalog={HATS} catalogId="hats" items={s.hats} setItems={x=>patch({hats:x})}/></div><section><div className="sectionTitle"><h2>VÝBAVA</h2><button className="startGear" title="Hoď na zavazadlo, levnou a užitečnou výstroj ze str. 27" onClick={addStartGear}>⚄ POČÁTEČNÍ VÝSTROJ</button><label className="minorTitle">STŘÍBRŇÁKY <input className="silver" type="number" value={s.silver} onChange={e=>patch({silver:+e.target.value})}/></label></div><List title="" kind="gear" catalog={GEAR} catalogId="gear" info="Velikost: 0 drobný, 1 běžně velký, 2+ velký." items={s.gear} setItems={x=>patch({gear:x})}/></section>
<button className="fold historyFold" onClick={()=>setHistoryOpen(!historyOpen)}>HISTORIE HODŮ <span>{historyOpen?'▾':'▸'}</span></button>{historyOpen&&<div className="rollHistory">{rollHistory.length===0?<p>Zatím žádné sdílené hody.</p>:rollHistory.map(r=><div className="historyRow" key={r.id}><b>{r.character}</b><span>{r.label}</span><span>k20: {r.die}</span><span>{r.mod>=0?'+':''}{r.mod}</span><strong>= {r.total}</strong>{r.luck&&<em>ŠTĚSTÍ</em>}{r.misfortune&&<em>SMŮLA</em>}</div>)}</div>}<button className="fold notesFold" onClick={()=>setNotes(!notes)}>POZNÁMKY <span>{notes?'▾':'▸'}</span></button>{notes&&<textarea value={s.notes} onChange={e=>patch({notes:e.target.value})}/>}<button className="fold" onClick={()=>setBg(!bg)}>POZADÍ <span>{bg?'▾':'▸'}</span></button>{bg&&<div className="background">{Object.entries(s.background).map(([k,v])=><label key={k}><b>{k.toUpperCase()}</b><textarea value={v} onChange={e=>patch({background:{...s.background,[k]:e.target.value}})}/><button className="bgDie" title="Náhodný výsledek – tabulky doplníme z příručky" onClick={()=>{const tables:Record<string,string[]>={'Kdo jsi?':BG_WHO,'Charakterová vada':BG_FLAWS,'Poznávací znamení':BG_MARKS,'Idiosynkrazie':BG_IDIO,'Nešťastné události a stavy':BG_EVENTS,'Důležitá věc':BG_IMPORTANT};const a=tables[k]||[];if(a.length){const n=Math.floor(Math.random()*a.length);patch({background:{...s.background,[k]:a[n]}});setRoll({label:k,result:n+1})}}}>⚄</button></label>)}</div>}<footer>Český digitální deník • testovací verze 0.9.1</footer>{roll&&<RollModal {...roll} onClose={()=>setRoll(null)}/>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
